apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safeguard.api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "safeguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "safeguard.api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "safeguard.api.fullname" . }}
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-config
            - secretRef:
                name: {{ $.Release.Name }}-secret
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory }}
              cpu: {{ .Values.api.resources.requests.cpu }}
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
              cpu: {{ .Values.api.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
