apiVersion: v1
kind: Service
metadata:
  name: {{ include "safeguard.api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "safeguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      {{- if eq .Values.api.serviceType "NodePort" }}
      nodePort: {{ .Values.api.nodePort }}
      {{- end }}
  selector:
    app: {{ include "safeguard.api.fullname" . }}
