apiVersion: v1
kind: Service
metadata:
  name: {{ include "safeguard.redis.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "safeguard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: {{ include "safeguard.redis.fullname" . }}
